### ISSUE TITLE
Current state of project

### ISSUE THREAD

**Issue by shashanktomar** [couchbaselabs/sync_gateway_admin_ui#48]
Looks like no more development is going on here. Few questions:

- is this project still active? The current dev branch is not even compiling.
- if the project is dead, is there an alternative on which couchbase community is working?
- if the project is still alive, will pull requests be accepted?

**Comment by tleyden** [comment]
The latest dev is on https://github.com/couchbaselabs/sync_gateway_admin_ui/tree/dev

It's something that will hopefully be high priority soon.  A lot of folks want this, including the core dev team.

**Comment by tleyden** [comment]
> if the project is still alive, will pull requests be accepted?

Yes, PR's welcome!
